# Generated by Django 3.2.3 on 2021-06-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210602_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('statistique', models.CharField(max_length=250)),
                ('nom_statistique', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
            },
        ),
        migrations.RemoveField(
            model_name='website',
            name='nom_statistique',
        ),
        migrations.RemoveField(
            model_name='website',
            name='statistique',
        ),
    ]
